# baseURL = ''
languageCode = 'zh'
title = 'AsyncOS'

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

[markup.tableOfContents]
  startLevel = 1

[[menu.after]]
  name = "仓库地址"
  url = "https://github.com/AsyncOS/AsyncOS.github.io"
  weight = 10

[params]
  BookTheme = 'auto'
  BookRepo = 'https://github.com/AsyncOS/AsyncOS.github.io'
  BookEditPath = 'edit/main'
  BookCommitPath = 'commit'
  BookDateFormat = 'Jan 2, 2006'
